<?php
/* @var $this Aoe_Scheduler_Block_Adminhtml_Timeline */
$_helper = $this->helper('aoe_scheduler/data'); /* @var $_helper Aoe_Scheduler_Helper_Data */
?>

<script>
    var SCHEDULER_TIMELINE_DATA_URL = '<?php echo $this->getUrl('*/*/data'); ?>';
</script>

<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="<?php echo $this->getHeaderWidth() ?>"><?php echo $this->getHeaderHtml() ?></td>
            <td class="form-buttons"><?php echo $this->getButtonsHtml() ?></td>
        </tr>
    </table>
</div>

<div id="maincontainer">

    <div id="contentwrapper">
        <div id="contentcolumn">
            <div class="timeline-box">
                <div class="timeline-panel" data-bind="style: { width: timelinePanelWidth }">

                    <div id="now" data-bind="style: { left: nowLinePos }"><div class="arrow"></div></div>

                    <div class="row hours">
                        <div class="timeline">
                            <!-- ko foreach: hours -->
                                <div class="hour"><span data-bind="text: label"></span></div>
                            <!-- /ko -->
                        </div>
                    </div>

                    <!-- ko foreach: jobs -->
                    <div class="row">
                        <div class="timeline" data-bind="css: 'timeline_'+code">
                            <!-- ko foreach: schedules -->
                            <div class="task" id="id_%s" data-bind="style: style, css: status, attr: { id: 'id_'+schedule_id}"></div>
                            <!-- /ko -->
                        </div>
                    </div>
                    <!-- /ko -->

                </div>
            </div>
        </div>
        <!-- id="contentcolumn" -->
    </div><!-- id="contentwrapper" -->




    <div id="leftcolumn">

        <div class="row hours">
            <div class="caption"></div>
        </div>

        <!-- ko foreach: jobs -->
        <div class="row">
            <div class="configuration">
                <span data-bind="text: code"></span>
            </div>
        </div>
        <!-- /ko -->

    </div><!-- id="leftcolumn" -->


</div><!-- id="maincontainer" -->