<?php /* @var $this Aoe_Scheduler_Block_Adminhtml_Timeline */ ?>

<script type="text/javascript">
    var SCHEDULER_TIMELINE_DATA_URL = '<?php echo $this->getUrl('*/*/data'); ?>';
</script>

<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="<?php echo $this->getHeaderWidth() ?>"><?php echo $this->getHeaderHtml() ?></td>
            <td class="form-buttons"><?php echo $this->getButtonsHtml() ?></td>
        </tr>
    </table>
</div>

<div data-bind="visible: !showUI()">
    <?php echo $this->__('Loading...'); ?>
</div>

<div id="maincontainer" data-bind="visible: showUI">

    <div id="contentwrapper">
        <div id="contentcolumn">
            <div class="timeline-box">
                <div class="timeline-panel" data-bind="style: { width: timelinePanelWidth }">

                    <div id="now" data-bind="style: { left: nowLinePos }"><div class="arrow"></div></div>

                    <div class="row hours">
                        <div class="timeline">
                            <!-- ko foreach: hours -->
                                <div class="hour"><span data-bind="text: label"></span></div>
                            <!-- /ko -->
                        </div>
                    </div>

                    <!-- ko foreach: { data: jobs, afterRender: $root.collisionDetection } -->
                    <div class="row">
                        <div class="timeline" data-bind="css: 'timeline_'+code">
                            <!-- ko foreach: schedules -->
                            <div class="task" id="id_%s" data-bind="style: style, css: status, attr: { id: 'id_'+schedule_id}"></div>
                            <!-- /ko -->
                        </div>
                    </div>
                    <!-- /ko -->

                </div>
            </div>
        </div>
        <!-- id="contentcolumn" -->
    </div><!-- id="contentwrapper" -->




    <div id="leftcolumn">

        <div class="row hours">
            <div class="caption"></div>
        </div>

        <!-- ko foreach: jobs -->
        <div class="row">
            <div class="configuration">
                <span data-bind="text: code"></span>
            </div>
        </div>
        <!-- /ko -->

    </div><!-- id="leftcolumn" -->


</div><!-- id="maincontainer" -->