<?php
/* @var $this Aoe_Scheduler_Block_Adminhtml_TimelineDetail */
$_schedule = $this->getSchedule();
$_helper = $this->helper('aoe_scheduler/data'); /* @var $_helper Aoe_Scheduler_Helper_Data */
?>

<div class="details">
	<div class="details-headline <?php echo $_schedule->getStatus(); ?>">
		<h3><?php echo $_schedule->getJobCode(); ?></h3>
	</div>
	<div class="details-content">
		<table>
			<tr>
				<td class="label">Status:</td><td><?php echo $_helper->decorateStatus($_schedule->getStatus()) ?></td>
			</tr>
			<tr>
				<td class="label">Created at:</td><td><?php echo $_helper->decorateTime($_schedule->getCreatedAt()); ?></td>
			</tr>
			<tr>
				<td class="label">Scheduled at:</td><td><?php echo $_helper->decorateTime($_schedule->getScheduledAt()); ?></td>
			</tr>
			<tr>
				<td class="label">Executed at:</td><td><?php echo $_helper->decorateTime($_schedule->getExecutedAt()); ?></td>
			</tr>
			<tr>
				<td class="label">Finished at:</td><td><?php echo $_helper->decorateTime($_schedule->getFinishedAt()); ?></td>
			</tr>
			<tr>
				<td class="label">Id:</td><td><?php echo $_schedule->getId(); ?></td>
			</tr>
		</table>
	</div>
</div>
